name: Deploy Notebooks to Databricks

on:
  push:
    branches:
      - main  # Set to the branch name you want to deploy from

jobs:
  deploy_notebooks:
    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Use compatible Python version for databricks-cli

    - name: Install Databricks CLI
      run: |
        python -m pip install --upgrade pip
        pip install databricks-cli

    - name: Configure Databricks CLI
      run: |
        $configDir = Join-Path $env:USERPROFILE ".databricks"
        New-Item -Path $configDir -ItemType Directory -Force
        $configFilePath = Join-Path $configDir "config"
        $content = "[DEFAULT]`nhost = ${{ secrets.DATABRICKS_HOST }}`ntoken = ${{ secrets.DATABRICKS_TOKEN }}"
        $content | Out-File -FilePath $configFilePath -Encoding UTF8 -Force
        Write-Output "Configured Databricks CLI profile at $configFilePath"

    - name: Deploy Notebooks to Databricks
      run: |
        databricks workspace import_dir ./curation/datatransformation /datatransformation --overwrite --profile DEFAULT
      env:
        DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
        DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
      shell: pwsh
