name: Deploy Notebooks to Databricks

on:
  push:
    branches:
      - main  # Set to the branch name you want to deploy from

jobs:
  deploy_notebooks:
    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # Python version should be compatible with databricks-cli

    - name: Install Databricks CLI
      run: pip install databricks-cli

    - name: Configure Databricks CLI
      run: |
        $configDir = Join-Path $env:USERPROFILE ".databricks"
        New-Item -ItemType Directory -Path $configDir -Force
        $configFilePath = Join-Path $configDir "config"
        $content = "[DEFAULT]`nhost = ${{ secrets.DATABRICKS_HOST }}`ntoken = ${{ secrets.DATABRICKS_TOKEN }}"
        $content | Out-File -FilePath $configFilePath -Encoding UTF8 -Force
        Write-Output "Config file created at: $configFilePath"
      shell: pwsh

    - name: Deploy Notebooks to Databricks
      run: |
        $configFilePath = Join-Path $env:USERPROFILE ".databricks\config"
        databricks --profile DEFAULT --config-file $configFilePath workspace import_dir ./curation/datatransformation /datatransformation --overwrite
      shell: pwsh

