name: Deploy to Databricks

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Databricks CLI
      run: |
        python -m pip install --upgrade pip
        pip install databricks-cli

    - name: Configure Databricks CLI
      env:
        DATABRICKS_HOST: ${{ secrets.DATABRICKS_WORKSPACE_URL }}
        DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
      run: |
        $configDir = "$env:USERPROFILE\.databricks"
        if (-Not (Test-Path -Path $configDir)) {
          New-Item -ItemType Directory -Path $configDir
        }
        $content = "[DEFAULT]`nhost = $env:DATABRICKS_HOST`ntoken = $env:DATABRICKS_TOKEN"
        $content | Out-File -FilePath "$configDir\config" -Encoding utf8 -Force

    - name: Deploy Notebooks
      run: databricks workspace import_dir curation/datatransformation /datatransformation --overwrite
